name: btsa
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - fbprophet
  - jupyter
  - jupyterlab
  - matplotlib
  - nb_conda_kernels
  - networkx
  - numpy
  - pandas
  - plotly
  - pymc3
  - pyramid
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - pip:
    - tensorflow
    - tensorflow-probability